### ISSUE TITLE
Errors while intalling

### ISSUE THREAD

**Issue by jfdezjambrina** [DAT-ETSIT/wolwebapp#2]
Dear sirs:
  At the end of instalation, just after confirm the email configuration I get the following errors:

> ¿Son correctos estos datos? (S/N) S
> /bin/python3: can't open file '/srv/wolwebapp/generateSecrets.py': [Errno 2] No such file or directory
> Traceback (most recent call last):
>   File "/srv/wolwebapp/wsgi.py", line 3, in <module>
>     from main import app
>   File "/srv/wolwebapp/main.py", line 11, in <module>
>     from routes import routes
>   File "/srv/wolwebapp/routes.py", line 11, in <module>
>     import mail.mail as mail
>   File "/srv/wolwebapp/mail/mail.py", line 5, in <module>
>     from cryptography.fernet import Fernet
> ModuleNotFoundError: No module named 'cryptography'
> 
> Configurando servicio.
> sed: no se puede leer /srv/wolwebapp/services/wolwebapp_part.service: No existe el fichero o el directorio
> sed: no se puede leer /srv/wolwebapp/services/wolwebapp_part.service: No existe el fichero o el directorio
> cp: no se puede efectuar `stat' sobre '/srv/wolwebapp/services/wolwebapp.target': No existe el fichero o el directorio
> Failed to enable unit: Unit file wolwebapp.target does not exist.
> Failed to start wolwebapp.target: Unit wolwebapp.target not found.
> 
> Instalación completada.

What I can do?

 Thanks very much,

**Comment by aLVaRoZz01** [comment]
Good afternoon Jose Luis, 

The error was due to a bug in the routes when configuring the email.

Fixed in the commit of March 17.

Best regards
